################################################################################
### generated-with:
###   type: R-package
###   name: kwb.pkgbuild
###   version: 0.2.1
###   installed-from: Github (kwb-r/kwb.pkgbuild@6c7b577)
###   installed-on: '2022-02-09'
### generated-by:
###   user: mrustl
###   function-call: kwb.pkgbuild::create_empty_branch_ghpages(pkg$name)
### generated-on: 2022-02-09 11:13:47
################################################################################


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
